<a href="https://colab.research.google.com/github/JiordaniE/Python_Projects/blob/main/Salaries_by_college_major.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
#import pandas
import pandas as pd

In [63]:
#read in csv file
df = pd.read_csv("salaries_by_college_major.csv")

In [64]:
#look at first 5 rows of the dataset
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [65]:
#see number of rows
df.shape #51 rows and 6 columns

(51, 6)

In [66]:
#get access to the column names
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [67]:
#look at the last 5 rows
df.tail() #there's missing data

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [68]:
#to get rid of the last row with missing values
clean_df = df.dropna()

In [69]:
#looking at last five rows, there aren't missing values
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [70]:
#get access to a particular column, "Starting Median Salary"
clean_df["Starting Median Salary"]

0    46,000.00
1    57,700.00
2    42,600.00
3    36,800.00
4    41,600.00
5    35,800.00
6    38,800.00
7    43,000.00
8    63,200.00
9    42,600.00
10   53,900.00
11   38,100.00
12   61,400.00
13   55,900.00
14   53,700.00
15   35,000.00
16   35,900.00
17   50,100.00
18   34,900.00
19   60,900.00
20   38,000.00
21   37,900.00
22   47,900.00
23   39,100.00
24   41,200.00
25   43,500.00
26   35,700.00
27   38,800.00
28   39,200.00
29   37,800.00
30   57,700.00
31   49,100.00
32   36,100.00
33   40,900.00
34   35,600.00
35   49,200.00
36   40,800.00
37   45,400.00
38   57,900.00
39   35,900.00
40   54,200.00
41   39,900.00
42   39,900.00
43   74,300.00
44   50,300.00
45   40,800.00
46   35,900.00
47   34,100.00
48   36,500.00
49   34,000.00
Name: Starting Median Salary, dtype: float64

In [73]:
#to get the highest starting salary just add ".max()"
clean_df["Starting Median Salary"].max()

74300.0

In [74]:
#to get the index of the major that earns $74,300, we use ".idxmax()" to find the row
clean_df["Starting Median Salary"].idxmax() #turns out to be 43

43

In [75]:
#to see the major associated with row 43, we use ".loc" for location with the column "Undergraduate Major"
clean_df["Undergraduate Major"].loc[43]

'Physician Assistant'

In [77]:
#this is the second way to find the major but with just brackets and the row number
clean_df["Undergraduate Major"] [43]

'Physician Assistant'

In [78]:
#to get the entire row, don't specify the column, but use ".loc"
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                         74,300.00
Mid-Career Median Salary                       91,700.00
Mid-Career 10th Percentile Salary              66,400.00
Mid-Career 90th Percentile Salary             124,000.00
Group                                               STEM
Name: 43, dtype: object

In [79]:
#get highest mid-career salary
print(clean_df['Mid-Career Median Salary'].max())

#get the row/index where it's located
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")

#get the major
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [80]:
#get the lowest starting salary
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [81]:
#get the lowest mid-career slary
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary               34,900.00
Mid-Career Median Salary             52,000.00
Mid-Career 10th Percentile Salary    29,300.00
Mid-Career 90th Percentile Salary   102,000.00
Group                                     HASS
Name: 18, dtype: object

In [82]:
#to get the difference between the 90th and 10th percentile salary of each major
clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0    109,800.00
1     96,700.00
2    113,700.00
3    104,200.00
4     85,400.00
5     96,200.00
6     98,100.00
7    108,200.00
8    122,100.00
9    102,700.00
10    84,600.00
11   105,500.00
12    95,900.00
13    98,000.00
14   114,700.00
15    74,800.00
16   116,300.00
17   159,400.00
18    72,700.00
19    98,700.00
20    99,600.00
21   102,100.00
22   147,800.00
23    70,000.00
24    92,000.00
25   111,000.00
26    76,000.00
27    66,400.00
28   112,000.00
29    88,500.00
30   115,900.00
31    84,500.00
32    71,300.00
33   118,800.00
34   106,600.00
35   100,700.00
36   132,900.00
37   137,800.00
38    99,300.00
39   107,300.00
40    50,700.00
41    65,300.00
42   132,500.00
43    57,600.00
44   122,000.00
45   126,800.00
46    95,400.00
47    66,700.00
48    87,300.00
49    65,400.00
dtype: float64

In [83]:
#add the risk of each major's salary into the dataframe as a column using ".insert"
spread_col = clean_df['Mid-Career 90th Percentile Salary'] -clean_df['Mid-Career 10th Percentile Salary']

#naming the column "Spread"
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

In [84]:
#to find the major with the lowest risk use ".sort_values()" method
low_risk = clean_df.sort_values("Spread")

#just looking at the major and spread
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major    Spread
40                     Nursing 50,700.00
43         Physician Assistant 57,600.00
41                   Nutrition 65,300.00
49                     Spanish 65,400.00
27  Health Care Administration 66,400.00

In [85]:
#sort the salaries to highest earning potentials
highest_potential = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending = False)

#show the top five careers of earning potentials
highest_potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                         210,000.00
22               Finance                         195,000.00
8   Chemical Engineering                         194,000.00
37                  Math                         183,000.00
44               Physics                         178,000.00

In [86]:
#sort the careers by spread in decsending order
highest_spread = clean_df.sort_values("Spread", ascending = False)

#show the top five careers of the highest spread
highest_spread[["Undergraduate Major", "Spread"]].head()

   Undergraduate Major     Spread
17           Economics 159,400.00
22             Finance 147,800.00
37                Math 137,800.00
36           Marketing 132,900.00
42          Philosophy 132,500.00

In [87]:
#getting the count of each major in the type of major, Business, HASS, and STEM
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [89]:
#get the average salary by group
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean(numeric_only = True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"